<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2023-04-10 13:50:25',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2023-09-19 06:37:41',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 1,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2023-09-18 06:10:24',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 2,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2022-10-22 18:45:46',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2026-02-06 07:47:24',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2023-09-19 06:37:41',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2022-10-22 18:47:59',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2022-10-22 18:47:59',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2022-10-22 18:47:59',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2022-10-22 16:56:24',
                'updated_at' => '2026-02-06 07:47:24',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Parámetros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-align-left',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2022-10-22 17:33:41',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2022-10-22 18:39:59',
                'updated_at' => '2026-02-06 07:47:24',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2022-10-22 19:14:59',
                'updated_at' => '2026-02-06 07:47:24',
                'route' => 'clear.cache',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 1,
                'created_at' => '2022-10-23 14:20:59',
                'updated_at' => '2024-05-05 21:30:18',
                'route' => 'voyager.people.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Préstamos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-hand-holding-dollar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-10-24 05:03:27',
                'updated_at' => '2023-02-26 03:07:09',
                'route' => 'loans.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Bóveda',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-vault',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-10-25 01:55:52',
                'updated_at' => '2022-10-25 01:56:08',
                'route' => 'vaults.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Cajeros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cash-register',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-10-25 16:36:14',
                'updated_at' => '2022-10-25 16:36:23',
                'route' => 'cashiers.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Rutas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-route',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 5,
                'created_at' => '2022-11-03 18:28:19',
                'updated_at' => '2024-12-04 21:48:58',
                'route' => 'voyager.routes.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Reportes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-chart-pie',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2022-12-05 21:07:39',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Recaudación',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 2,
                'created_at' => '2022-12-05 21:09:12',
                'updated_at' => '2023-02-11 22:26:41',
                'route' => 'print.dailyCollection',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Lista Diaria Cobro',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 6,
                'created_at' => '2022-12-05 21:10:11',
                'updated_at' => '2023-09-18 06:06:58',
                'route' => 'print.dailyList',
                'parameters' => 'null',
            ),
            21 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Deudores Atrazados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 1,
                'created_at' => '2022-12-13 14:46:48',
                'updated_at' => '2022-12-15 15:38:27',
                'route' => 'print-loanListLate',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Recaudacion Diaria',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 4,
                'created_at' => '2022-12-23 13:48:24',
                'updated_at' => '2023-09-18 06:06:49',
                'route' => 'print-loanCollection',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 39,
                'menu_id' => 1,
                'title' => 'Prestamos Entregados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 5,
                'created_at' => '2023-02-09 03:22:51',
                'updated_at' => '2023-09-18 06:06:54',
                'route' => 'print-loanDelivered',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Cambios de Rutas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-right-left',
                'color' => '#000000',
                'parent_id' => 11,
                'order' => 7,
                'created_at' => '2023-02-12 00:31:27',
                'updated_at' => '2024-12-04 21:48:58',
                'route' => 'routes-loan-exchange.index',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Prestamos Totales',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 3,
                'created_at' => '2023-04-25 17:59:28',
                'updated_at' => '2023-04-25 17:59:35',
                'route' => 'print-loanAll',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 46,
                'menu_id' => 1,
                'title' => 'Empeño',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-handshake',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2023-06-11 12:02:56',
                'updated_at' => '2025-03-10 21:00:28',
                'route' => 'pawn.index',
                'parameters' => 'null',
            ),
            27 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Categorías de actículos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 2,
                'created_at' => '2023-09-19 07:22:49',
                'updated_at' => '2024-12-04 21:49:01',
                'route' => 'voyager.item-categories.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 50,
                'menu_id' => 1,
                'title' => 'Datos de actículos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => 11,
                'order' => 4,
                'created_at' => '2023-09-19 07:24:43',
                'updated_at' => '2024-12-04 21:48:58',
                'route' => 'voyager.item-features.index',
                'parameters' => 'null',
            ),
            29 => 
            array (
                'id' => 52,
                'menu_id' => 1,
                'title' => 'Tipos de artículo',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 3,
                'created_at' => '2023-09-23 19:32:14',
                'updated_at' => '2024-12-04 21:48:58',
                'route' => 'voyager.item-types.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 54,
                'menu_id' => 1,
                'title' => 'Reporte General',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 7,
                'created_at' => '2024-04-30 17:28:42',
                'updated_at' => '2024-04-30 17:28:48',
                'route' => 'print.general',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 55,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-folder',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2024-05-05 21:30:11',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 56,
                'menu_id' => 1,
                'title' => 'Cargos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 55,
                'order' => 2,
                'created_at' => '2024-05-05 21:41:35',
                'updated_at' => '2024-05-05 21:41:50',
                'route' => 'voyager.employe-jobs.index',
                'parameters' => NULL,
            ),
            33 => 
            array (
                'id' => 58,
                'menu_id' => 1,
                'title' => 'Gastos Adicionales',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => NULL,
                'parent_id' => 55,
                'order' => 3,
                'created_at' => '2024-05-06 20:38:35',
                'updated_at' => '2024-11-10 19:50:16',
                'route' => 'voyager.expenses.index',
                'parameters' => NULL,
            ),
            34 => 
            array (
                'id' => 59,
                'menu_id' => 1,
                'title' => 'Periodos de pagos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 6,
                'created_at' => '2024-06-02 06:20:32',
                'updated_at' => '2024-12-04 21:48:58',
                'route' => 'voyager.payments-periods.index',
                'parameters' => NULL,
            ),
            35 => 
            array (
                'id' => 60,
                'menu_id' => 1,
                'title' => 'Encargados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 55,
                'order' => 4,
                'created_at' => '2024-07-29 00:32:40',
                'updated_at' => '2025-03-10 21:00:19',
                'route' => 'voyager.managers.index',
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 61,
                'menu_id' => 1,
                'title' => 'Egresos/Gastos Adicionales',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 8,
                'created_at' => '2024-07-29 01:03:32',
                'updated_at' => '2024-12-05 01:00:42',
                'route' => 'report.registers.index',
                'parameters' => 'null',
            ),
            37 => 
            array (
                'id' => 65,
                'menu_id' => 1,
                'title' => 'Adm. Asistencia',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-clipboard-user',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2024-11-05 05:29:42',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => NULL,
                'parameters' => '',
            ),
            38 => 
            array (
                'id' => 66,
                'menu_id' => 1,
                'title' => 'Importar Asistencias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-file-import',
                'color' => '#000000',
                'parent_id' => 65,
                'order' => 1,
                'created_at' => '2024-11-05 05:31:29',
                'updated_at' => '2024-11-05 05:33:10',
                'route' => 'attendances.index',
                'parameters' => 'null',
            ),
            39 => 
            array (
                'id' => 67,
                'menu_id' => 1,
                'title' => 'Horarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-clock',
                'color' => '#000000',
                'parent_id' => 65,
                'order' => 2,
                'created_at' => '2024-11-05 05:32:53',
                'updated_at' => '2024-11-05 05:33:04',
                'route' => 'hours.index',
                'parameters' => NULL,
            ),
            40 => 
            array (
                'id' => 68,
                'menu_id' => 1,
                'title' => 'Turnos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-calendar-days',
                'color' => '#000000',
                'parent_id' => 65,
                'order' => 3,
                'created_at' => '2024-11-05 08:01:19',
                'updated_at' => '2024-11-05 08:01:31',
                'route' => 'shifts.index',
                'parameters' => NULL,
            ),
            41 => 
            array (
                'id' => 69,
                'menu_id' => 1,
                'title' => 'Sanciones Por Retrazo',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-file-invoice-dollar',
                'color' => '#000000',
                'parent_id' => 65,
                'order' => 4,
                'created_at' => '2024-11-10 05:47:30',
                'updated_at' => '2024-11-10 20:02:30',
                'route' => 'voyager.late-penalties.index',
                'parameters' => 'null',
            ),
            42 => 
            array (
                'id' => 70,
                'menu_id' => 1,
                'title' => 'Sanciones Por Faltas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-minus',
                'color' => NULL,
                'parent_id' => 65,
                'order' => 5,
                'created_at' => '2024-11-10 06:11:53',
                'updated_at' => '2024-11-10 06:13:03',
                'route' => 'voyager.penalty-fouls.index',
                'parameters' => NULL,
            ),
            43 => 
            array (
                'id' => 71,
                'menu_id' => 1,
                'title' => 'Contratos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-file-signature',
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 5,
                'created_at' => '2024-11-10 18:32:14',
                'updated_at' => '2025-03-10 21:00:19',
                'route' => 'contracts.index',
                'parameters' => NULL,
            ),
            44 => 
            array (
                'id' => 72,
                'menu_id' => 1,
                'title' => 'Pagos de Planillas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-file-invoice-dollar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2024-11-10 19:49:55',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => 'paymentSheet.index',
                'parameters' => 'null',
            ),
            45 => 
            array (
                'id' => 73,
                'menu_id' => 1,
                'title' => 'Panillas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-sheet-plastic',
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 6,
                'created_at' => '2024-11-20 10:06:22',
                'updated_at' => '2025-03-10 21:00:19',
                'route' => 'spreadsheets.index',
                'parameters' => NULL,
            ),
            46 => 
            array (
                'id' => 74,
                'menu_id' => 1,
                'title' => 'Categorías de Gastos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-shop',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 1,
                'created_at' => '2024-12-04 21:45:00',
                'updated_at' => '2024-12-04 21:49:01',
                'route' => 'voyager.cashier-movement-categories.index',
                'parameters' => NULL,
            ),
            47 => 
            array (
                'id' => 75,
                'menu_id' => 1,
                'title' => 'Planilla de Aguinaldos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-money-check-dollar',
                'color' => '#000000',
                'parent_id' => 55,
                'order' => 7,
                'created_at' => '2024-12-25 21:03:11',
                'updated_at' => '2025-03-10 21:00:19',
                'route' => 'bonus.index',
                'parameters' => NULL,
            ),
            48 => 
            array (
                'id' => 76,
                'menu_id' => 1,
                'title' => 'Historial Lista Diaria',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-landmark',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 14,
                'created_at' => '2025-01-02 03:52:21',
                'updated_at' => '2025-01-30 14:33:53',
                'route' => 'history-dailyList.index',
                'parameters' => NULL,
            ),
            49 => 
            array (
                'id' => 77,
                'menu_id' => 1,
                'title' => 'Prestamos Por Gestion',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 9,
                'created_at' => '2025-01-05 03:35:14',
                'updated_at' => '2025-01-05 03:57:14',
                'route' => 'print.loanGestion',
                'parameters' => 'null',
            ),
            50 => 
            array (
                'id' => 78,
                'menu_id' => 1,
                'title' => 'Prestamos Por Rango de Gestión',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 10,
                'created_at' => '2025-01-05 14:36:03',
                'updated_at' => '2025-01-05 14:39:11',
                'route' => 'print.loanRangeGestion',
                'parameters' => 'null',
            ),
            51 => 
            array (
                'id' => 79,
                'menu_id' => 1,
                'title' => 'Detalle de Pago por Gestión',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 11,
                'created_at' => '2025-01-05 14:36:47',
                'updated_at' => '2025-01-05 14:44:44',
                'route' => 'print.loanDetailGestion',
                'parameters' => 'null',
            ),
            52 => 
            array (
                'id' => 80,
                'menu_id' => 1,
                'title' => 'Recolección Diaria %',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 12,
                'created_at' => '2025-01-22 09:46:48',
                'updated_at' => '2025-01-22 09:46:55',
                'route' => 'print.bonusCollection',
                'parameters' => NULL,
            ),
            53 => 
            array (
                'id' => 81,
                'menu_id' => 1,
                'title' => 'Prestamos Recuperación',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-handshake',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2025-01-29 13:07:08',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => 'loanRecoveries.index',
                'parameters' => NULL,
            ),
            54 => 
            array (
                'id' => 82,
                'menu_id' => 1,
                'title' => 'Prestamos en Recuperacion',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 13,
                'created_at' => '2025-01-30 14:11:40',
                'updated_at' => '2025-01-30 15:41:17',
                'route' => 'print.loanRecovery',
                'parameters' => 'null',
            ),
            55 => 
            array (
                'id' => 83,
                'menu_id' => 1,
                'title' => 'Inventario',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-box-open',
                'color' => '#000000',
                'parent_id' => 85,
                'order' => 2,
                'created_at' => '2025-02-26 21:08:05',
                'updated_at' => '2025-03-10 21:00:23',
                'route' => 'inventories.index',
                'parameters' => NULL,
            ),
            56 => 
            array (
                'id' => 84,
                'menu_id' => 1,
                'title' => 'Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-shop',
                'color' => '#000000',
                'parent_id' => 85,
                'order' => 1,
                'created_at' => '2025-02-27 20:21:11',
                'updated_at' => '2025-03-10 21:00:23',
                'route' => 'sales.index',
                'parameters' => NULL,
            ),
            57 => 
            array (
                'id' => 85,
                'menu_id' => 1,
                'title' => 'Gestión de Inventario',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-people-carry-box',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2025-03-10 20:59:53',
                'updated_at' => '2025-04-21 03:27:35',
                'route' => NULL,
                'parameters' => '',
            ),
            58 => 
            array (
                'id' => 86,
                'menu_id' => 1,
                'title' => 'Reporte Inventarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 85,
                'order' => 3,
                'created_at' => '2025-03-10 21:01:56',
                'updated_at' => '2025-03-10 23:04:55',
                'route' => 'print.inventories',
                'parameters' => 'null',
            ),
            59 => 
            array (
                'id' => 87,
                'menu_id' => 1,
                'title' => 'Reporte Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 85,
                'order' => 4,
                'created_at' => '2025-03-10 23:04:19',
                'updated_at' => '2025-03-10 23:04:38',
                'route' => 'print.sales',
                'parameters' => 'null',
            ),
            60 => 
            array (
                'id' => 91,
                'menu_id' => 1,
                'title' => 'Compras de Salarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-wallet',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2025-04-21 03:27:15',
                'updated_at' => '2025-05-14 02:01:59',
                'route' => 'salary-purchases.index',
                'parameters' => 'null',
            ),
            61 => 
            array (
                'id' => 92,
                'menu_id' => 1,
                'title' => 'Reportes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-chart-pie',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2026-02-06 07:46:48',
                'updated_at' => '2026-02-06 07:47:24',
                'route' => NULL,
                'parameters' => '',
            ),
            62 => 
            array (
                'id' => 93,
                'menu_id' => 1,
                'title' => 'Prestamos Vigentes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 1,
                'created_at' => '2026-02-06 07:50:34',
                'updated_at' => '2026-02-12 12:57:58',
                'route' => 'reports-loans.currentloans',
                'parameters' => NULL,
            ),
            63 => 
            array (
                'id' => 94,
                'menu_id' => 1,
                'title' => 'Prestamos x Gestion',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 2,
                'created_at' => '2026-02-06 11:03:04',
                'updated_at' => '2026-02-12 12:57:58',
                'route' => 'reports-loans.loanGestions',
                'parameters' => NULL,
            ),
            64 => 
            array (
                'id' => 95,
                'menu_id' => 1,
                'title' => 'Prestamos X Rango Gestion',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 3,
                'created_at' => '2026-02-12 12:57:39',
                'updated_at' => '2026-02-12 12:57:56',
                'route' => 'reports-loans.loanRangeGestions',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}